name: aws_iot_device
description: A wrapper around MQTT to make it easier to connect to AWS IoT.
version: 0.1.0
homepage: https://bitbucket.org/TheBosZ/aws_iot_device/
author: Nathan Kerr <nathankerr@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  amazon_cognito_identity_dart: ^0.0.20
  mqtt:
    git: https://github.com/TheBosZ/mqtt.dart.git #https://github.com/chenhuawei/mqtt.dart.git
  tuple: ^1.0.2

dev_dependencies:
  test: ^1.0.0
